IBM/lunchpail

cmd/subcommands/assemble.go, pkg/fe/assembler/assemble.go, pkg/fe/assembler/emit.go, pkg/fe/assembler/options.go, pkg/fe/assembler/platforms.go
This is to facilitate building a set of assembled binaries across supported GOOS and GOARCH.
=> feat: add --all-platforms/-A option to assemble

.github/workflows/actions.yml, cmd/subcommands/init/local.go, cmd/subcommands/up.go, hack/init.sh, pkg/lunchpail/init/kind.go, pkg/lunchpail/init/local.go, pkg/util/term.go, tests/bin/deploy-tests.sh, tests/bin/travis/setup.sh
This also updates the CI tests to improve test coverage of the create-cluster code paths.
=> feat: improve local UX with up --create-cluster and --watch by default

charts/workstealer/templates/containers/workstealer.yaml, charts/workstealer/templates/s3/config.yaml, charts/workstealer/templates/s3/secret.yaml, charts/workstealer/templates/s3/service.yaml, pkg/fe/linker/configure.go, tests/tests/test7f-repo/preinit.sh, tests/tests/test7f/preinit.sh
This should help us to distinguish lunchpail-provided internal s3 from application-provided services named "s3". Though we already had the run name in the service name, this should hopefully further help us to distinguish *our* service.
Also fixes test7f/preinit.sh, which didn't handle the case where the `rcloneremotetest` config had changed. Also refactors the workstealer chart to place some of the s3 bits under a subdirectory.
=> fix: update internal minio service name to include 'lunchpail'

docs/demos/README.md
Also use `uname` to avoid hard-coding os and arch in the example `curl` command line.
=> doc: update demo docs to reflect --create-namespace changes

cmd/subcommands/up.go
We previously hadn't used `-t` as it had been a shorthand for `--openshift`. However, #60 removed that option in favor of inferring it (i.e. determining whether the target is openshift automatically, for the user)
=> feat: up --target-platform/-p -> --target/-t

cmd/subcommands/assemble.go, pkg/fe/assembler/assemble.go, pkg/fe/assembler/stage.go, tests/bin/deploy-tests.sh
Fixes #68 
Closes #67 
In contrast to #67, this PR keeps source as a positional parameter. Adds test coverage.
=> feat: allow for re-assembly i.e. `assemble` against an assembled binary

charts/workstealer/src/workstealer.sh, charts/workstealer/templates/containers/workstealer.yaml
this removes the double indirection `${!variable}` that was confusing and also required bash rather than dash (which is often /bin/sh)
=> fix: clean up workstealer queue variables

charts/workstealer/src/workstealer.sh, charts/workstealer/templates/containers/workstealer.yaml, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/workstealer/lower.go
See pkg/fe/transformer/api/queue.go
Starting with the workstealer. This also continues #81 to clean up workstealer shell variables even further.
=> fix: begin consolidation of queue prefix path logic

charts/shell/templates/containers/main.yaml, charts/workerpool/templates/queue.yaml, images/components/lunchpail-worker-watcher/main.go, pkg/fe/transformer/api/datasets.go, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/shell/lower.go, pkg/fe/transformer/api/workerpool/lower.go
This continues the work of #81 and #82 to consolidate the queue variables. This extends to ensure that all envs use the same variable prefix naming scheme, from shell to workerpool to workstealer.
=> fix: continue consolidate of queue variables

charts/shell/prestop.sh, charts/shell/templates/containers/main.yaml, charts/workerpool/templates/containers/app.yaml, charts/workerpool/templates/queue.yaml, charts/workstealer/src/workstealer.sh, charts/workstealer/templates/containers/workstealer.yaml, images/components/lunchpail-worker-watcher/main.go, pkg/fe/transformer/api/dispatch/parametersweep/main.sh, pkg/fe/transformer/api/dispatch/s3/main.sh, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/shell/lower.go, pkg/fe/transformer/api/workerpool/lower.go
This continues #81 #82 #83 by consolidating the queue variables for the workerpool and shell components.
=> fix: clean up workerpool and shell queue variables

charts/workerpool/templates/job.yaml, images/components/lunchpail-worker-watcher/main.go, pkg/be/kubernetes/updates.go, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/observe/qstat/stream.go
We had been doing some ugly implicit logic about how to specify and intuit queue filepaths w.r.t. pool name and worker name. This simplifies that all and consolidates the logic further into api/queue.go.
=> fix: clean up handling of queue paths

charts/workstealer/src/minio.sh, charts/workstealer/src/workstealer.sh, images/components/lunchpail-workstealer/Dockerfile
saves 64 megabytes, plus this should help with unifying the workstealer into a singular lunchpail image.
this removes unnecessary reliance on bash in the workstealer logic
=> feat: update workstealer image to use alpine rather than debian slim

charts/shell/prestop.sh, charts/shell/templates/containers/main.yaml, charts/shell/templates/pod.yaml, charts/shell/templates/prestop.yaml
with `lunchpail qdone` we no longer need a shell script with volume/volumeMount/configMap.
=> chore: clean out prestop shell script in charts/shell

charts/workstealer/templates/containers/workstealer.yaml
This removes some stragglers left behind by #142
=> fix: remove remnants of internal s3 from workstealer chart

.dockerignore, Dockerfile
We were correctly using `go mod download` to cache dependencies in an image layer... but we are also using the hack/setup/cli.sh to build the CLI, which *also* did a go mod download...
=> fix: restructure Dockerfile to avoid proliferation of 1.8Gi image build layers

charts/minio/templates/job.yaml, charts/shell/templates/pod.yaml, charts/templates/rbac.yaml, charts/templates/scc.yaml, charts/workerpool/templates/job.yaml, charts/workstealer/templates/job.yaml, pkg/be/backend.go, pkg/be/ibmcloud/values.go, pkg/be/kubernetes/values.go, pkg/be/platform/values.go, pkg/fe/compile.go, pkg/fe/linker/configure.go, pkg/fe/transformer/api/dispatch/parametersweep/lower.go, pkg/fe/transformer/api/dispatch/s3/lower.go, pkg/fe/transformer/api/minio/lower.go, pkg/fe/transformer/api/shell/lower.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/fe/transformer/api/workerpool/lowerall.go, pkg/fe/transformer/api/workstealer/lower.go, pkg/fe/transformer/application.go, pkg/fe/transformer/lower.go
There are currently two circumstances that require a service account:
1. user specified image pull secret
2. backend needs it, e.g. for an OpenShift SecurityContextConstraint
=> fix: only create and use service account if needed

charts/shell/templates/pod.yaml, pkg/fe/transformer/api/minio/minio.sh, pkg/fe/transformer/api/minio/transpile.go, pkg/fe/transformer/api/shell/lower.go, pkg/runtime/queue/s3.go
In tests/bin/helpers.sh we try to pull out info about the queue after the test has passed. But minio self-destructs, and prior to this PR, it does so without any termination grace period.
=> fix: add sleep before exit in minio and terminationGracePeriodSeconds when running tests

pkg/fe/linker/configure.go, pkg/fe/template/chart/templates/default-queue.yaml, pkg/fe/template/chart/templates/image-pull-secret.yaml, pkg/fe/template/chart/templates/namespace.yaml, pkg/fe/template/chart/templates/rbac.yaml, pkg/fe/template/chart/templates/scc.yaml, pkg/fe/transformer/api/shell/chart/templates/podspec.yaml, pkg/fe/transformer/api/shell/lower.go, tests/tests/test0b/pail/app.yaml, tests/tests/test7-wait-withfail/pail/dataset-secret.yaml, tests/tests/test7-wait/pail/dataset-secret.yaml, tests/tests/test7/pail/dataset-secret.yaml, tests/tests/test7b/pail/dataset-secret.yaml, tests/tests/test7c/pail/dataset-secret.yaml, tests/tests/test7e-by-role-autorun/pail/dataset-secret.yaml, tests/tests/test7e-by-role-autorun/pail/dataset.yaml, tests/tests/test7e-by-role/pail/dataset-secret.yaml, tests/tests/test7e-by-role/pail/dataset.yaml, tests/tests/test7e/pail/dataset-secret.yaml, tests/tests/test7e/pail/dataset.yaml, tests/tests/test7h/pail/dataset-secret.yaml
Places more lunchpail (rather than application- or user-provided) values under a lunchpail.xxx subtree
BREAKING CHANGE: Values.user and Values.uid become Values.lunchpail.user.name and Values.lunchpail.user.uid
BREAKING CHANGE: Values.namespace.user becomes .Release.Namespace
BREAKING CHANGE: Values.taskqueue becomes Values.lunchpail.taskqueue
=> refactor: further simplify template values in configure.go

pkg/fe/compile.go, pkg/fe/linker/configure.go, pkg/fe/transformer/api/shell/chart/templates/job.yaml, pkg/fe/transformer/api/shell/chart/templates/pod.yaml, pkg/fe/transformer/api/shell/chart/templates/service.yaml, pkg/fe/transformer/api/shell/chart/templates/workdir.yaml, pkg/fe/transformer/api/shell/lower.go, pkg/fe/transformer/api/template.go, pkg/fe/transformer/lower.go, pkg/ir/llir/application_instance.go, tests/tests/test7f/pail/worker.yaml
this allows us to skip some duplicate values in shell/lower that are also in linker/configure. we can now skip passing through (oddly) service account from configure to lower
=> feat: pass through yaml values to transformer

pkg/fe/transformer/api/shell/chart/templates/podlabels.yaml, pkg/fe/transformer/api/shell/chart/templates/service.yaml, pkg/fe/transformer/api/shell/lower.go
BREAKING CHANGE: this may break ancient charts
This also consolidates some of the pod and service labeling in charts/shell
=> feat: remove Values.enclosingRun

cmd/subcommands/info.go, pkg/be/runs/pretty.go
- eliminates the superfluous use of charmbracelet from pkg/be
- adds go:build tag to info command
19.2Mi -> 18.1Mi for the image
9.8Mi -> 8.8Mi for the binary build (in the image)
Overall, down from 60Mi for the binary build (in the image)
=> fix: trim more from the image builds

pkg/be/kubernetes/shell/chart/templates/containers/main.yaml, pkg/be/kubernetes/shell/template.go, pkg/runtime/queue/s3.go, pkg/runtime/workstealer/report.go, pkg/runtime/workstealer/run.go
This should enable clients pulling the info from the queue, rather than having to interact with the cluster logging mechanisms directly.
For now, we continue (also) to log to the qstat stream to stderr, so that the pkg/observe logic doesn't need to change (yet).
=> feat: log qstat info to a file in the queue folder

pkg/be/kubernetes/shell/template.go, pkg/fe/transformer/api/minio/transpile.go, pkg/runtime/queue/copyin.go, pkg/runtime/workstealer/run.go, tests/bin/add-data.sh
- the tests run in verbose mode, which results in a huge volume of output from the minio server, causing test failures. for now, back this out.
- copy-in rclone needs more retries
- for local testing, minio should also sleep before exit
- (minor) add-data.sh helper script now specifies -c main to avoid spurious console output
- workstealer may fail due to bucket not (yet) existing
=> fix: stabilize tests

pkg/be/backend.go, pkg/be/ibmcloud/down.go, pkg/be/ibmcloud/null.go, pkg/be/kubernetes/namespace.go, pkg/be/kubernetes/streamer-null.go, pkg/boot/down.go
Also, this function does not need to accept a compilationName, as the impl can get it directly from the compilation API.
=> refactor: rename backend.DeleteNamespace() to backend.Purge()

pkg/be/backend.go, pkg/be/ibmcloud/api.go, pkg/be/ibmcloud/create.go, pkg/be/ibmcloud/down.go, pkg/be/ibmcloud/dryrun.go, pkg/be/ibmcloud/new-options.go, pkg/be/ibmcloud/new.go, pkg/be/ibmcloud/null.go, pkg/be/ibmcloud/up.go, pkg/be/kubernetes/down.go, pkg/be/kubernetes/marshal.go, pkg/be/kubernetes/streamer-null.go, pkg/be/kubernetes/up.go, pkg/be/new.go, pkg/boot/up.go, pkg/fe/prepare-run.go, pkg/ir/linked.go
so that boot/up does not need to hard-coded kubernetes this also helps us eliminate a few more lingering uses of Namespace outside of the backend impls
=> feat: introduce backend.DryRun

pkg/be/ibmcloud/create.go, pkg/be/ibmcloud/down.go, pkg/be/ibmcloud/up.go, pkg/boot/up.go, pkg/fe/prepare-run.go, pkg/ir/linked.go
=> fix: remove superfluous Runname from Linked struct

pkg/be/backend.go, pkg/be/ibmcloud/create.go, pkg/be/ibmcloud/down.go, pkg/be/ibmcloud/dryrun.go, pkg/be/ibmcloud/up.go, pkg/be/kubernetes/apply.go, pkg/be/kubernetes/common/options.go, pkg/be/kubernetes/down.go, pkg/be/kubernetes/marshal.go, pkg/be/kubernetes/up.go, pkg/be/kubernetes/values.go, pkg/fe/prepare-run.go, pkg/ir/llir/llir.go, pkg/ir/llir/options.go
this avoids having to import pkg/compilation in addition to important pkg/ir/llir
=> fix: further simplify options in backend by having llir.Options

pkg/fe/linker/configure.go, pkg/fe/transformer/api/minio/lower.go, pkg/fe/transformer/lower.go
When using an external task queue via `--queue`, we want internals3 minio to be disabled and not lowered as a separate component.
=> fix: no minio component with external s3

cmd/subcommands/logs.go, hack/setup/cli.sh, pkg/be/ibmcloud/logs.go, pkg/be/kubernetes/logs.go, pkg/be/streamer/streamer.go, pkg/observe/logs.go, tests/bin/deploy-tests.sh, tests/bin/helpers.sh, tests/bin/run.sh, tests/bin/undeploy-tests.sh
This also adds a `--tail` option to the lunchpail logs command.
=> feat: port tests/bin/helpers.sh from kubectl logs to lunchpail logs

tests/bin/helpers.sh
this removes another use of kubectl in helpers.sh
=> test: remove unused `local queue=` shell variable in tests/bin/helpers.sh

tests/bin/helpers.sh
this removes another use of kubectl in helpers.sh
=> test: update the second run_name= in helpers.sh

pkg/fe/transformer/api/minio/transpile.go, tests/bin/ci.sh, tests/bin/helpers.sh
this isn't particularly helpful at this point.
this removes another use of kubectl in helpers.sh
=> test: eliminate watch from helpers.sh

cmd/options/components.go, cmd/options/target.go, cmd/subcommands/cpu.go, cmd/subcommands/down.go, cmd/subcommands/logs.go, cmd/subcommands/qlast.go, cmd/subcommands/qstat.go, cmd/subcommands/run.go, cmd/subcommands/run/instances.go, cmd/subcommands/run/list.go, cmd/subcommands/status.go, cmd/subcommands/up.go, pkg/be/backend.go, pkg/be/ibmcloud/instances.go, pkg/be/kubernetes/instances.go, pkg/lunchpail/component.go, tests/bin/helpers.sh
- this reports the number of instances of a given component
- also changes lunchpail runs to lunchpail run list
- also updates helpers.sh to use it, which removes another use of kubectl in helpers.sh
=> feat: lunchpail run instances

cmd/subcommands/qin.go, go.mod, go.sum, pkg/be/kubernetes/portforward.go, pkg/be/kubernetes/wait.go, pkg/runtime/queue/copyin.go, tests/bin/add-data.sh, tests/bin/run.sh
- fixes be/kubernetes/portforward to wait for the target pod to be ready
- removes hopefully the final use of kubectl in tests/bin (we had missed add-data.sh in the previous PRs)
=> feat: update qin to support running in compiled mode

pkg/fe/linker/queue/rclone.go, tests/bin/add-data.sh, tests/bin/run.sh, tests/tests/test7-security-context/preinit.sh, tests/tests/test7-wait/preinit.sh, tests/tests/test7/preinit.sh, tests/tests/test7b/preinit.sh, tests/tests/test7f/preinit.sh
we were using this to update the default rclone config. this updates the test logic to use a per-test rclone config file. this should be safer (we will avoid modifying a non-lunchpail common config file), and makes it easier to eliminate the rclone CLI dependence.
=> fix: eliminate rclone CLI dependence from tests

cmd/subcommands/minio/server.go
we had one sleep in the cmd and another in the pkg
=> fix: minio server command sleeps twice before exit

pkg/be/kubernetes/up.go, pkg/fe/linker/configure.go, pkg/fe/linker/queue/spec.go
- moves that service address to be/kubernetes
- introduces Queue.UpdateEndpoint() api
=> fix: front-end has kubernetes-specific queue endpoint (service address)

pkg/be/kubernetes/shell/datasets.go, pkg/be/kubernetes/shell/template.go, pkg/fe/linker/queue/rclone.go, tests/tests/test7-security-context/preinit.sh, tests/tests/test7-wait/preinit.sh, tests/tests/test7/preinit.sh, tests/tests/test7b/preinit.sh, tests/tests/test7f/preinit.sh
this also allows us to avoid having copies of preinit.sh, and instead we can have one and share via symlink
=> fix: avoid kubernetes-isms in test rclone config

cmd/options/compile.go, cmd/options/target.go, cmd/subcommands/compile.go, cmd/subcommands/cpu.go, cmd/subcommands/down.go, cmd/subcommands/logs.go, cmd/subcommands/qcat.go, cmd/subcommands/qin.go, cmd/subcommands/qlast.go, cmd/subcommands/qls.go, cmd/subcommands/qstat.go, cmd/subcommands/run/instances.go, cmd/subcommands/run/list.go, cmd/subcommands/status.go, cmd/subcommands/up.go, pkg/be/new.go, pkg/be/target/platform.go, pkg/boot/down.go, pkg/compilation/compilation.go, pkg/compilation/options.go, pkg/fe/compiler/compile.go, pkg/fe/linker/configure.go, pkg/fe/prepare-run.go, pkg/observe/info/model.go, pkg/observe/info/ui.go, tests/bin/add-data.sh, tests/bin/compile.sh
- cleans up the TargetOptions, consolidating the Namespace flag from compilation.Options into compilation.Target.Namespace, and adding compilation.Target.Platform that was previously a be-specific option, via be.TargetOptions
- cleans up the cmd/ logic to consolidate adding target options and adding compilation options
- save/restore compilationOptions.json via embed
- fixes for overrideValues and overrideFileValues
- test coverage currently in compile.sh compileTimeTarget
=> feat: allow --target to be provided at compile time

cmd/subcommands/cpu.go, cmd/subcommands/down.go, cmd/subcommands/logs.go, cmd/subcommands/qlast.go, cmd/subcommands/qstat.go, cmd/subcommands/status.go, cmd/subcommands/up.go, pkg/be/backend.go, pkg/be/ibmcloud/logs.go, pkg/be/ibmcloud/qstat.go, pkg/be/ibmcloud/streamer.go, pkg/be/ibmcloud/updates.go, pkg/be/ibmcloud/utilization.go, pkg/be/kubernetes/events.go, pkg/be/kubernetes/logs.go, pkg/be/kubernetes/qstat.go, pkg/be/kubernetes/streamer.go, pkg/be/kubernetes/updates.go, pkg/be/kubernetes/utilization.go, pkg/be/local/streamer.go, pkg/be/streamer/streamer.go, pkg/boot/down.go, pkg/boot/up.go, pkg/observe/cpu/ui.go, pkg/observe/logs.go, pkg/observe/qstat/qlast.go, pkg/observe/qstat/ui.go, pkg/observe/status/stream.go, pkg/observe/status/ui.go
The goal is to avoid closed channels by wrapping everything in a context tree.
This also updates the Streamer API to move the common bits (runname and, now, context) to the constructor and away from the instance methods.
=> fix: pass through context to streamer APIs

cmd/subcommands/cpu.go, cmd/subcommands/down.go, cmd/subcommands/init/local.go, cmd/subcommands/logs.go, cmd/subcommands/qcat.go, cmd/subcommands/qin.go, cmd/subcommands/qlast.go, cmd/subcommands/qls.go, cmd/subcommands/qstat.go, cmd/subcommands/run/instances.go, cmd/subcommands/run/list.go, cmd/subcommands/status.go, cmd/subcommands/up.go, pkg/be/backend.go, pkg/be/ibmcloud/ok.go, pkg/be/kubernetes/ok.go, pkg/be/local/ok.go, pkg/be/new.go, pkg/lunchpail/init/local.go, tests/bin/up.sh
This also adjusts the behavior of `up` so that it only creates a cluster if the user passes `--create-cluster`. Unfortunately, create-cluster is not currently a compile-time flag, but still this seems the safer option for now.
=> fix: backend.Ok() should accept a context

cmd/subcommands/compile.go, pkg/be/kubernetes/common/template.go, pkg/fe/compiler/compile.go, pkg/fe/compiler/options.go, tests/tests/test7-wait/pail/dispatcher.yaml
Third PR of the log verbose/debug setup set of PRs... (first one https://github.com/IBM/lunchpail/pull/276, second one #277 )
Cleaning up verbose bool as parameter in many places, and use directly from compilationOptions
=> fix: removing verbose as parameter and use compilationOptions cont..

cmd/subcommands/cpu.go, pkg/be/controller/controller.go, pkg/be/events/component.go, pkg/be/events/updates.go, pkg/be/kubernetes/pool.go, pkg/be/kubernetes/updates.go, pkg/be/local/streamer.go, pkg/observe/cpu/ui.go, pkg/observe/status/model.go, pkg/observe/status/worker.go
The concept of namespace should be isolated to the backend impls.
=> fix: remove some remnants of namespace in pkg/observe

pkg/be/kubernetes/shell/chart/templates/podlabels.yaml, pkg/be/kubernetes/shell/template.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/ir/llir/shell.go
This adds a GroupName field to llir.ShellComponent to allow for this distinction between instance name and ... pool name
=> fix: restore original pool name label

tests/bin/helpers.sh
A recent change resulted in `--verbose` being persisted as a compilation option. As a result, the test validators spew out lots of verbose output when validating log output -- as the logs command obeys --verbose, too.
=> test: reduce verbosity of test output vs logs

pkg/fe/transformer/api/dispatch/parametersweep/main.sh
one of them isn't guarded by DEBUG
=> fix: parametersweep dispatcher has two printenvs

cmd/subcommands/up.go, pkg/boot/down.go, pkg/fe/linker/configure.go, pkg/fe/prepare-run.go
It had become a wrapper over compilation.Options
=> refactor: eliminate linker.ConfigureOptions

pkg/boot/up.go, pkg/fe/prepare-run.go
- it included flags not needed for PrepareForRun -- move these to boot.UpOptions
- otherwise, it was only a wrapper over compilation.Options, hence eliminate!
=> refactor: eliminate fe.CompileOptions

pkg/boot/up.go, pkg/fe/prepare-run.go
PrepareForRun should not be modifying the compilation options it is given.
=> refactor: no need to return compilation options from PrepareForRun

cmd/subcommands/qin.go, pkg/runtime/queue/copyin.go
i.e. rather than just a single one, to allow callers to amortize the cost of setting up the AccessQueue
=> feat: update runtime/queue/CopyIn to accept an array of files/paths to copy in

cmd/subcommands/upload.go, pkg/runtime/queue/upload.go, pkg/runtime/queue/upload/upload.go, tests/bin/add-data.sh
This is to avoid confusion with the *other* way we have been using "copy in", to mean "copy in to the worker/pod". I think that other meaning is better, because it aligns with existing "copy-in/copy-out" terminology. What we really meant by qin is "upload from my laptop to the s3/queue storage".
=> feat: rename qin/copyin -> upload

pkg/runtime/queue/enqueue.go
rather than duplicating the verbose and debug fields
=> refactor: upload queue/Enqueue*Options to embed compilation.LogOptions

pkg/be/local/streamer.go
We were passing Logger=nil to the Tail package, which is what its docs state will result in using its default logger. Unfortunately we rather see a null pointer segfault.
=> fix: local backend segfaults with `up --verbose`

pkg/fe/builder/build.go
Two problems: kubernetes is not happy with underscores; and s3 is not either for a bucket name.
=> fix: avoid underscores in build.Name

pkg/boot/up.go
We were fmt.Printf’ing something that returned a pair `(string, error)`
Fixes #187
=> fix: `up --dry-run` with kubernetes backend emits trailing EXTRA nil garbage

pkg/runtime/queue/s3.go, pkg/runtime/queue/wait.go
Also:
- refactor cleanups to consolidate s3 waiting logic in the existing wait.go file
- simplify the existing polling logic to call Lsf on the specific file we are looking for
=> fix: `queue add --wait` should use notification when available

pkg/runtime/queue/paths.go, pkg/runtime/queue/wait.go, pkg/runtime/worker/watcher.go, pkg/runtime/workstealer/run.go
This updates the Listen() implementation:
- return (chan string, chan error) instead of the minio Notification channel
- list first, then watch, and re-list after first notification; this patches the two race windows in the minio bucket notification (it does not send notifications for objects already in existence)
Fixes #364
=> fix: push notifications may miss some objects

pkg/runtime/worker/watcher.go
It was always moving processing to outbox, ignoring any output from the worker.
=> fix: if worker emits a task to `$2` the worker watcher ignores this

.gitignore, pkg/be/kubernetes/queue.go, pkg/boot/enqueue.go, pkg/boot/up.go, pkg/ir/llir/llir.go, pkg/util/term.go, tests/bin/run.sh, tests/tests/test7-up-dispatch/post.sh
This updates test7-up-dispatch for coverage, and adds support for a `post.sh` in tests that will be run to allow for custom post-completion validation.
=> feat: if user passes inputs on `up` command line, copy outputs back when done

pkg/runtime/worker/watcher.go
=> fix: add a few more messages to help with worker-watcher debugging

pkg/runtime/worker/watcher.go
We currently print the full path to the task file.
=> fix: worker-watcher logs handler errors with internal path names

pkg/boot/enqueue.go, pkg/runtime/queue/client.go, pkg/runtime/queue/ls.go, pkg/runtime/queue/qcat.go, pkg/runtime/queue/upload.go
rather than passing back a stop function as a separate return value that needs to be propagated around by the caller
=> refactor: upew NewS3ClientForRun to return a stoppable client

pkg/boot/io.go, pkg/boot/up.go, pkg/runtime/builtins/cat.go, pkg/runtime/builtins/redirect.go
This is entirely refactoring, there should be neither features nor semantic changes.
=> refactor: split out the upload and download logic into builtins.Cat() and builtins.Redirect()

cmd/subcommands/component/workstealer/run.go, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/workstealer/lower.go, pkg/fe/transformer/api/workstealer/transpile.go, pkg/runtime/workstealer/assess.go, pkg/runtime/workstealer/fetch.go, pkg/runtime/workstealer/report.go, pkg/runtime/workstealer/run.go
this removes the complex combination of env vars and implicit logic to encode s3 queue paths in favor of passing explicit paths on the command line. this lets us consolidate the logic in the front-end. the runtime only uses the explicit paths as given.
TODO: this only cleans up the workstealer
=> fix: first pass of cleaning up s3 paths: workstealer

cmd/subcommands/component/worker/prestop.go, cmd/subcommands/component/worker/run.go, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/runtime/worker/options.go, pkg/runtime/worker/run.go, pkg/runtime/worker/watcher.go
this should consolidate the remaining bits
=> fix: second pass at cleaning up runtime/worker queue paths

tests/bin/run.sh, tests/bin/up.sh
Previously, up --watch meant to use the "modal"/full screen status UI which breaks tests. Now that we aren't doing that, it is helpful to watch during tests so that we can see worker logs.
=> test: enable watch mode for tests

pkg/be/kubernetes/queue.go
We were only avoiding ports <1000
=> fix: be/kubernetes should avoid ports <1024

pkg/be/backend.go, pkg/be/ibmcloud/queue.go, pkg/be/kubernetes/common/values.go, pkg/be/kubernetes/queue.go, pkg/be/kubernetes/shell/chart/templates/containers/main.yaml, pkg/be/kubernetes/shell/template.go, pkg/be/local/queue.go, pkg/be/local/shell/spawn.go, pkg/be/streamer/qstat.go, pkg/fe/transformer/api/queue.go, pkg/fe/transformer/api/shell/lower.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/ir/llir/shell.go, pkg/runtime/queue/client.go, pkg/runtime/queue/paths.go
the queue path work #434 renders the notion of "queue prefix path" obsolete.
=> refactor: remove 'QueuePrefixPath' as it is no longer needed

cmd/subcommands/cat.go, pkg/runtime/builtins/add1.go, tests/bin/pipelines.sh
This adds `add1 | add1 | add1` pipeline tests.
This adds an `add1` command... until we have support for a `run -e` to allow for ad-hoc command line worker functions, i’ll add an add1 builtin (alongside the cat builtin) to help with tests/demos
=> test: add1 pipeline tests

.github/workflows/tests.yml, cmd/subcommands/needs/python.go, pkg/fe/transformer/api/shell/lower.go, pkg/runtime/needs/install_requirements.go, pkg/runtime/needs/python.go, tests/bin/run.sh, tests/tests/python-code-code-quality/target, tests/tests/python-code-code2parquet/target, tests/tests/python-language-doc-chunk/target, tests/tests/python-language-doc-quality/target, tests/tests/python-language-html2parquet/target, tests/tests/python-language-lang-id/target, tests/tests/python-language-pdf2parquet/target, tests/tests/python-language-text-encoder/target, tests/tests/python-universal-doc-id/target, tests/tests/python-universal-ededup/target, tests/tests/python-universal-filter/target, tests/tests/python-universal-resize/target, tests/tests/python-universal-tokenization/target
Fixes #430 
Tests that run on target=kubernetes using Datasets restricted to `local` target until writeBlobsToWorkdir is implemented for K8. Some other tests also running on local only due to other known errors like large model, etc
=> fix: needs python to run in K8; backend agnostic rqmts install

pkg/be/local/shell/spawn.go, tests/bin/pipelines.sh
This updates the local backend to install the spawned processes in a process group, and monitors for context cancellation. Upon cancellation, it kills the process group.
On its own, Go seems only to kill the top of the process tree upon context cancellation. Sigh.
=> fix: on failure loitering 'minio server' processes may remain

pkg/be/local/shell/spawn.go, pkg/boot/up.go, pkg/runtime/queue/s3.go, pkg/runtime/worker/prestop.go
- runtime/worker/prestop was invoking s3.Touch() which had an in-built retry, even if minio was already gone
- boot/up needs to respond to SIGINT by cancelling context
=> fix: worker prestop and other helper processes may loiter

pkg/ir/queue/as.go, pkg/ir/queue/for.go, pkg/runtime/builtins/redirect.go, pkg/runtime/queue/wait.go
This was due to using the wrong path for Failed files.
=> fix: stderr output of failing tasks was not being reported

cmd/options/build.go, cmd/options/calling-conventions.go, cmd/subcommands/component/worker/run.go, pkg/boot/failures.go, pkg/boot/io.go, pkg/boot/up.go, pkg/build/options.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/ir/hlir/application.go, pkg/ir/hlir/calling-convention.go, pkg/ir/queue/as.go, pkg/ir/queue/pattern.go, pkg/runtime/builtins/redirect.go, pkg/runtime/worker/options.go, pkg/runtime/worker/process-task.go, tests/bin/pipelines.sh
Adds support for workers accepting input on stdout and producing output on stdout.
This adds add1c and add1d test coverage in pipelines.sh. add1d also adds python test coverage for pipelines. Also adds mix-and-match pipelines, where we mix-and-match calling conventions, and python vs bash.
Improved pipeline error handling and error handling test coverage.
Separate task failure watching from redirect logic.
Currently, we cannot stream the input stream directly from s3 into the stdin of the worker. This is because currently the inbox->processing->outbox flow (needed by the workstealer) is not separate from the data to be processed. We will need to keep them separate, somehow. So that the inbox->processing->outbox flow is done with markers, and the underlying data is placed in a separate …
=> feat: calling-convention=stdio

tests/tests/python-code-code-quality/pail/data/requirements.txt, tests/tests/python-code-code2parquet/pail/data/requirements.txt, tests/tests/python-code-header-cleanser/pail/data/requirements.txt, tests/tests/python-language-doc-chunk/pail/data/requirements.txt, tests/tests/python-language-doc-quality/pail/data/requirements.txt, tests/tests/python-language-html2parquet/pail/data/requirements.txt, tests/tests/python-language-lang-id/pail/data/requirements.txt, tests/tests/python-language-pdf2parquet/pail/data/requirements.txt, tests/tests/python-language-pii-redactor/pail/data/requirements.txt, tests/tests/python-language-text-encoder/pail/data/requirements.txt, tests/tests/python-universal-doc-id/pail/data/requirements.txt, tests/tests/python-universal-ededup/pail/data/requirements.txt, tests/tests/python-universal-filter/pail/data/requirements.txt, tests/tests/python-universal-resize/pail/data/requirements.txt, tests/tests/python-universal-tokenization/pail/data/requirements.txt
we can probably update to 18+, but we will have to re-generate expected output as pyarrow 18 seems to have resulted in a binary format change
Note: some of the python tests have transitive constraints on pyarrow <17... hence the <18 constraint we use
=> test: pin pyarrow<18

pkg/be/local/streamer.go, pkg/observe/qstat/ui.go
full width, purple
> the weird color for the unassigned row is due to a breaking change in lipgloss/table (see below) and is a regression from #472 which bumped our dependencies
no header, natural width, gray table borders, devote colors to distinguish states (queued, in-progress, ...), combine all of the global numbers into a single row called "inbox", show pool name in a column, pretty-print worker name to remove run name and pool name.
this also updates to breaking changes in lipgloss/table. Apparently now passed to the StyleFunc, the header row has row index -1 (previously 0).
=> fix: tweak queue stats console ui

go.mod, go.sum
We forgot to run `go mod tidy` in #475
=> chore: go mod tidy to remove unused dependences

tests/bin/up.sh
kubernetes validators are a bit slower due to the need to open a port-forward to minio
=> test: increase SLEEP_BEFORE_EXIT for kubernetes

pkg/fe/transformer/api/shell/lower.go, pkg/runtime/needs/install_requirements.go
- We were not failing fast if needs failed #474
- We were re-issuing `python -m venv` even if the cached venv already existed. This, combined with the poor error failing of  #474 resulted in a bunch of odd failures.
Fixes #474
=> fix: improve error handling for needs and don't re-create venv

pkg/observe/queuestreamer/fetch.go, pkg/observe/queuestreamer/model.go, pkg/observe/queuestreamer/patterns.go, pkg/observe/queuestreamer/stream.go, pkg/runtime/workstealer/assess.go, pkg/runtime/workstealer/report.go, pkg/runtime/workstealer/run.go
This should enable us to reuse the queue model fetching for the `queue stats` command (which currently uses a separate path for fetching and parsing a model, and even that model is separate from the one used by the workstealer)
new `pkg/observe/queuestreamer.StreamModel()`
=> refactor: update workstealer code to separate workstealer-specific logic from queue model fetching

cmd/subcommands/queue/stat.go, go.mod, go.sum, pkg/observe/qstat/ui.go, pkg/runtime/queue/client.go
This is in place of the separate path of pkg/be/streamer.QueueStats() which fed off the stdout "reports" from the workstealer. With this change, `queue stat` feeds directly off push notifications from minio (if supported).
This also introduces the use of a debouncer in qstat.UI to avoid flurries of output.
=> feat: update `queue stat` to use new pkg/observe/queuestreamer

pkg/observe/qstat/renderer.go, pkg/observe/qstat/ui.go
We had an erroneous notion of "is final step" and inbox vs outbox.
=> fix: queue stat has bugs when displaying multiple steps

pkg/runtime/needs/install_darwin.go, pkg/runtime/needs/minio.go
We call `os.LookPath("minio")` but on Linux, we install minio in a special place that may not be on PATH when we call LookPath.
=> fix: needs minio on linux downloads minio multiple times

hack/pipeline-demo.sh, pkg/be/local/shell/spawn.go, pkg/be/local/shell/workdir.go, pkg/fe/transformer/api/workstealer/transpile.go, pkg/fe/transformer/application.go, pkg/observe/qstat/renderer.go, pkg/observe/qstat/ui.go, pkg/observe/queuestreamer/fetch.go, pkg/observe/queuestreamer/model.go, pkg/observe/queuestreamer/stream.go, pkg/runtime/builtins/redirect.go, pkg/runtime/queue/wait.go, pkg/runtime/workstealer/assess.go, pkg/runtime/workstealer/report.go, pkg/runtime/workstealer/run.go, tests/bin/helpers.sh, tests/bin/run.sh
This reduces overhead, but mainly helps to fix a lingering problem: the `readyToBye` logic as implemented with one workstealer per step resulted in later steps potentially exiting as they would think no more work remained (depending on race windows...). With a single workstealer, it can keep track of this status across the entire pipeline.
Also:
- add more steps to pipeline-demo.sh
- update queue stat UI so that it updates in place, rather than scrolling a new table for every update
- update workstealer to debounce the queuestreamer.Model channel -- no point in having the workstealer respond to every single update to the queue, as long as it eventually responds
- avoids 'unexpected EOF' errors from `queue stat`
=> feat: use a single workstealer for entire pipeline

pkg/ir/queue/listen.go, pkg/ir/queue/paths.go, pkg/runtime/queue/ls.go, tests/bin/helpers.sh
The workstealer and queue stat don't need to receive updates for stdout/stderr/code files.
=> fix: move stdout/stderr/code files out of main queue paths

cmd/subcommands/queue/cat.go, cmd/subcommands/queue/drain.go, cmd/subcommands/queue/ls.go, cmd/subcommands/queue/upload.go, hack/dpk.sh, pkg/be/backend.go, pkg/be/ibmcloud/queue.go, pkg/be/kubernetes/logs.go, pkg/be/kubernetes/portforward.go, pkg/be/kubernetes/queue.go, pkg/be/local/queue.go, pkg/boot/alldone.go, pkg/boot/failures.go, pkg/boot/io.go, pkg/boot/up.go, pkg/observe/logs.go, pkg/observe/qstat/stream.go, pkg/runtime/builtins/cat.go, pkg/runtime/queue/client.go, pkg/runtime/queue/drain.go, pkg/runtime/queue/ls.go, pkg/runtime/queue/qcat.go, pkg/runtime/queue/upload.go
This touches a lot of files, because we have updated `be.Backend.AccessQueue()` to require a `build.LogOptions`. This also removes `be.Backend.Queue()` from the public API.
=> fix: improve log and portforward output for be/kubernetes

pkg/boot/alldone.go, pkg/boot/failures.go, pkg/boot/up.go, pkg/observe/queuestreamer/stream.go, pkg/runtime/builtins/redirect.go, pkg/runtime/queue/client.go, pkg/runtime/queue/s3.go, pkg/runtime/queue/upload.go, pkg/runtime/queue/wait.go, pkg/runtime/worker/watcher.go, pkg/runtime/workstealer/assess.go, pkg/runtime/workstealer/run.go
- improved detection of errors from ibmcloud
- boot/up had assumed that the minio component would disappear as part of its cleanup logic
- clean up boot/alldone to call the simpler WaitTillExists() API
- a few other bug fixes in the way the polling varying of Listen() API worked; e.g. we weren't properly avoiding re-notifying on existing objects when polling
=> fix: various fixes for non-minio s3 endpoints

cmd/subcommands/component/worker/prestop.go, cmd/subcommands/component/worker/run.go, hack/pipeline-demo.sh, pkg/be/backend.go, pkg/be/ibmcloud/ok.go, pkg/be/kubernetes/ok.go, pkg/be/kubernetes/queue.go, pkg/be/local/ok.go, pkg/be/new.go, pkg/boot/alldone.go, pkg/boot/failures.go, pkg/boot/io.go, pkg/fe/prepare-run.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/lunchpail/init/kind.go, pkg/observe/qstat/stream.go, pkg/runtime/builtins/cat.go, pkg/runtime/builtins/redirect.go, pkg/runtime/minio/server.go, pkg/runtime/queue/client.go, pkg/runtime/queue/drain.go, pkg/runtime/queue/ls.go, pkg/runtime/queue/qcat.go, pkg/runtime/queue/qdone.go, pkg/runtime/queue/upload.go, pkg/runtime/worker/prestop.go, pkg/runtime/worker/run.go, pkg/runtime/worker/watcher.go, pkg/runtime/workstealer/run.go, tests/bin/pipelines.sh
- updates `pipeline-demo.sh` so that when it is running in kubernetes mode, it actually does a mix of local and kubernetes
- updates `pipeline-demo.sh` to launch a separate minio, and fixed some issues with using it. this should give us some test coverage for a “remote/hosted” s3. it aws also necessary to support mixed kubernetes-local.
- fixes a couple of bugs with run context (missing step) and with this mix-mode and with pipelines versus external/hosted s3
- fixes a race condition in the workstealer caused by the use of the debouncer
=> fix: multiple bugs for mixed local-kubernetes pipelines

hack/pipeline-demo.sh
This is output from `minio server` resulting from pipeline-demo.sh killing it at the end.
=> fix: hack/pipeline-demo.sh ends with `INFO: Exiting on signal: TERMINATED`

pkg/be/kubernetes/common/chart/templates/default-queue.yaml, pkg/be/kubernetes/common/values.go, pkg/be/kubernetes/names/queue.go, pkg/be/kubernetes/queue.go, pkg/be/kubernetes/shell/chart/templates/job.yaml, pkg/be/kubernetes/shell/datasets.go, pkg/be/kubernetes/shell/template.go, pkg/fe/linker/queue/rclone.go, pkg/ir/llir/context.go, pkg/ir/llir/llir.go
e.g. in a pipeline, if multiple stages all point to the same queue, we had been creating one kubernetes secret for each. With this update, the secret name is instead based on a hash of the queue spec.
=> fix: avoid multiple kubernetes Secrets storing the same data

.github/workflows/tests.yml
Fixes this warning:
> The following actions use a deprecated Node.js version
=> test: update to actions/cache@v4

cmd/options/build.go, cmd/subcommands/component/worker/run.go, pkg/build/options.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/runtime/worker/options.go, pkg/runtime/worker/run.go, pkg/runtime/worker/watcher.go, tests/tests/python-language-pdf2parquet/settings.sh
Also adds a `--pack` build option
```go
// Run k concurrent tasks; if k=0 and machine has N cores, then k=N
Pack int `yaml:",omitempty"`
```
Fixes #25
python-language-pdf2parquet currently requires `--pack=1` due to https://github.com/JaidedAI/EasyOCR/issues/1335
Maybe we can add some kind of lockfile support to help out the workers. Though they would still need to do the fcntl themselves.
=> feat: update worker watcher to "pack" i.e. leverage as many cores as the pod/machine provides

pkg/runtime/worker/process-task.go, pkg/runtime/worker/watcher.go, tests/tests/python-language-pdf2parquet/pail/src/main.py, tests/tests/python-language-pdf2parquet/settings.sh
Update python-language-pdf2parquet to use it, avoiding the need for --pack=1
=> feat: pass in a lockfile to workers

.github/workflows/tests.yml, pkg/be/kubernetes/shell/chart/templates/containers/main.yaml, pkg/lunchpail/init/kind.go, pkg/lunchpail/init/local.go, pkg/runtime/needs/install_requirements.go, tests/bin/build.sh, tests/bin/ci.sh, tests/bin/pipelines.sh, tests/bin/undeploy-tests.sh, tests/bin/up.sh
Also:
- use `pip install -q` unless verbose
- use `pip install --no-cache-dir` in kubernetes
- run non-verbose by default
=> fix: wrap venv installation with an flock LOCK_EX

tests/tests/python-language-doc-chunk/pail/data/requirements.txt
see https://github.com/run-llama/llama_index/issues/17016
=> fix: pin pydantic==2.9.2 to fix doc-chunk test failures

cmd/options/build.go, cmd/subcommands/component/worker/run.go, demos/pipelines/run.sh, pkg/build/options.go, pkg/fe/transformer/api/workerpool/lower.go, pkg/runtime/worker/options.go, pkg/runtime/worker/process-task.go, tests/tests/python-code-code-quality/post.sh, tests/tests/python-code-code-quality/settings.sh
Advantages:
- less network traffic
- cosmetically, for demos we can avoid the use of named pipes `<(gunzip -c input.gz)`
Disadvantages:
- extra cpu consumption on the worker side
- if using `files` calling convention, extra disk space consumption on the worker (to contain the gunzipped file *and* the gzipped file)
Test coverage in python-code-code-quality
TODOs:
- uncompress while downloading the task, rather than downloading and then gunzipping (this would eliminate the second disadvantage)
- update the rest of the python-* examples to use --gunzip rather than named pipes
=> feat: support passing through gzipped files, uncompressing them on the worker side

pkg/fe/transformer/api/shell/lower.go
Only remove if we find the requirements.txt file we stashed there.
=> fix: safeguard dangerous auto-clean feature
