- cmd/subcommands/down.go
- cmd/subcommands/up.go
- pkg/assembly/options.go
- pkg/be/delegation.go
- pkg/be/kubernetes/ok.go
- pkg/be/kubernetes/updates.go
- pkg/be/platform/Platform.go
- pkg/boot/down.go
- pkg/boot/up.go
- pkg/observe/events/updates.go
- pkg/observe/status/model.go
This also refactors the be.Platform to be a type rather than just a string; moved to be/pkg/Platform to avoid cyclic imports
> feat: be.Ok() API and update up() to use it as a prereq

- pkg/be/ibmcloud/authenticate.go
- pkg/be/ibmcloud/create.go
- pkg/be/ibmcloud/discovery.go
- pkg/be/ibmcloud/ok.go
This also preflight validates the auth.
> feat: support bearer token auth for ibmcloud target

- charts/templates/default-queue.yaml
- pkg/fe/linker/configure.go
There were some ugly leftovers from an earlier time.
> fix: clean up default-queue secret

- pkg/fe/transformer/api/dispatch/parametersweep/transpile.go
- pkg/fe/transformer/api/dispatch/s3/transpile.go
- pkg/fe/transformer/application.go
- pkg/ir/hlir/api.go
- pkg/ir/hlir/application.go
- tests/tests/test0b/pail/app.yaml
- tests/tests/test7/pail/app.yaml
- tests/tests/test7b/pail/app.yaml
- tests/tests/test7c/pail/app.yaml
- tests/tests/test7d/pail/app.yaml
- tests/tests/test7e-by-role-autorun/pail/app.yaml
- tests/tests/test7e-by-role/pail/app.yaml
- tests/tests/test7e/pail/app.yaml
- tests/tests/test7f-by-role-autorun-autodispatcher/pail/logic/worker.yaml
- tests/tests/test7f-external/settings.sh
- tests/tests/test7f-repo/pail/app.yaml
- tests/tests/test7f/pail/worker.yaml
- tests/tests/test7g/pail/app.yaml
- tests/tests/test7g/pail/workdispatcher-app.yaml
- tests/tests/test7h/pail/app.yaml
- tests/tests/test8/settings.sh
- tests/tests/test8b/settings.sh
> feat: remove unnecessary api: field of Application

- cmd/subcommands/up.go
> fix: up subcommand positional argument validation

- pkg/be/kubernetes/shell/chart/templates/containers/main.yaml
- pkg/be/kubernetes/shell/chart/templates/job.yaml
- pkg/be/kubernetes/shell/chart/templates/podlabels.yaml
- pkg/be/kubernetes/shell/chart/templates/prestop.yaml
- pkg/be/kubernetes/shell/chart/templates/workdir.yaml
- pkg/fe/linker/configure.go
- pkg/fe/template/chart/templates/scc.yaml
- pkg/fe/transformer/api/shell/lower.go
Values.name -> Values.lunchpail.name
Values.partOf -> Values.lunchpail.partOf
Values.component -> Values.lunchpail.component
> feat: a bit more lunchpail.xxx namespacing of lunchpail-provided template values

- pkg/be/backend.go
- pkg/be/ibmcloud/runs.go
- pkg/be/ibmcloud/updates.go
- pkg/be/kubernetes/events.go
- pkg/be/kubernetes/namespace.go
- pkg/be/kubernetes/runs.go
- pkg/be/kubernetes/updates.go
- pkg/be/runs/util/singleton.go
- pkg/be/runs/util/wait.go
- pkg/be/streamer/streamer.go
- pkg/boot/down.go
- pkg/observe/cpu/ui.go
- pkg/observe/logs.go
- pkg/observe/qstat/qlast.go
- pkg/observe/qstat/ui.go
- pkg/observe/status/stream.go
- pkg/observe/status/ui.go
this can be picked up from compilation.Name() when and if needed
> fix: remove some lingering "appname" variables scattered throughout

- pkg/be/kubernetes/pool.go
- pkg/be/kubernetes/shell/chart/templates/job.yaml
- pkg/be/kubernetes/shell/chart/templates/workdir.yaml
- pkg/be/kubernetes/shell/name.go
- pkg/be/kubernetes/shell/template.go
- pkg/util/dns1035.go
This consolidates the resource naming logic for the kubernetes backend.
> fix: shift +/- does not change pool size

- pkg/be/backend.go
- pkg/be/ibmcloud/create.go
- pkg/be/ibmcloud/down.go
- pkg/be/ibmcloud/dryrun.go
- pkg/be/ibmcloud/up.go
- pkg/be/kubernetes/apply.go
- pkg/be/kubernetes/common/options.go
- pkg/be/kubernetes/down.go
- pkg/be/kubernetes/marshal.go
- pkg/be/kubernetes/up.go
- pkg/be/kubernetes/values.go
- pkg/be/options/cli.go
- pkg/boot/up.go
This removes be/options/CliOptions in favor of compilation.Options
> fix: simplify/consolidate opts in the backend

- pkg/be/ibmcloud/create.go
> fix:target=ibmcloud components workstealer and workdispatcher default sa not found

- cmd/subcommands/runs.go
- tests/bin/helpers.sh
this removes another use of kubectl in helpers.sh
> feat: runs command and update helpers.sh to use it

- tests/bin/helpers.sh
this removes another use of kubectl from helpers.sh
> test: eliminate unused waitForStatus in helpers.sh

- pkg/fe/transformer/api/minio/transpile.go
- pkg/fe/transformer/api/workstealer/transpile.go
- pkg/runtime/minio/server.go
- pkg/runtime/queue/enqueue.go
- pkg/runtime/workstealer/run.go
- pkg/util/sleep.go
- tests/bin/helpers.sh
- tests/tests/test7-wait/settings.sh
this removes a few more uses of kubectl in helper.sh
> test: eliminate unnecessary kubectl waits from helper.sh

- cmd/subcommands/qcat.go
- cmd/subcommands/qls.go
- go.mod
- go.sum
- pkg/be/backend.go
- pkg/be/ibmcloud/queue.go
- pkg/be/kubernetes/common/chart/templates/default-queue.yaml
- pkg/be/kubernetes/common/values.go
- pkg/be/kubernetes/portforward.go
- pkg/be/kubernetes/queue.go
- pkg/fe/linker/queue/name.go
- pkg/fe/linker/queue/rclone.go
- pkg/ir/llir/llir.go
- pkg/runtime/queue/client.go
- pkg/runtime/queue/qcat.go
- pkg/runtime/queue/qls.go
- pkg/runtime/queue/s3.go
- tests/bin/helpers.sh
- introduces `backend.AccessQueue()` which manages port forward e.g. in the case of kubernetes.
- elimnates remaining uses of kubectl in helpers.sh
> feat: qls and qcat in compiled mode

- pkg/be/kubernetes/runs.go
If there is some error that results in the workerpool jobs not starting (e.g. initcontainer hangups), then lunchpail thinks there are no runs, even though the *other* resources are all there.
> fix: update kubernetes ListRuns to look for pods not jobs

- cmd/subcommands/qout.go
- pkg/be/kubernetes/shell/datasets.go
- pkg/runtime/queue/copyout.go
- pkg/runtime/queue/s3.go
- tests/bin/deploy-tests.sh
- tests/bin/rerun.sh
update kubernetes initContainer to use it rather than rclone
> feat: lunchpail copyout

- pkg/be/kubernetes/shell/datasets.go
- pkg/be/kubernetes/shell/template.go
- pkg/fe/transformer/api/shell/lower.go
this allows us to leverage the same copyout impl across backends
> feat: move copyout impl from be/kubernetes into fe/transformer

- pkg/be/ibmcloud/create.go
> fix: job parallelism for all VSIs together can be more than requested worker bug

- cmd/options/compile.go
- cmd/options/logs.go
- cmd/subcommands/compile.go
- cmd/subcommands/cpu.go
- cmd/subcommands/down.go
- cmd/subcommands/enqueue/file.go
- cmd/subcommands/images/build.go
- cmd/subcommands/init/local.go
- cmd/subcommands/logs.go
- cmd/subcommands/qstat.go
- cmd/subcommands/status.go
- cmd/subcommands/up.go
- docs/build/README.md
- pkg/compilation/options.go
First of a small set of PRs to add different levels of logging to most cmds..
> fix: adding verbose + debug flags 

- cmd/subcommands/enqueue/file.go
- cmd/subcommands/enqueue/s3.go
- pkg/boot/down.go
- pkg/fe/transformer/api/dispatch/parametersweep/main.sh
- pkg/fe/transformer/api/dispatch/parametersweep/transpile.go
- pkg/fe/transformer/api/dispatch/s3/transpile.go
- pkg/ir/hlir/parametersweep.go
- pkg/ir/hlir/processS3Objects.go
- pkg/runtime/queue/enqueue.go
Fixing error in tests:
```
Error: unknown flag: --verbose
Usage:
lunchpail enqueue file <file> [flags]
```
> fix: unknown --verbose in lunchpail enqueue file

- cmd/subcommands/logs.go
- pkg/lunchpail/component.go
> fix: support minio component logs

- pkg/runtime/minio/server.go
This cleans up some of the goroutine logic.
> fix: clean up `minio server` code

- pkg/be/local/files/files.go
- pkg/be/local/runs.go
- pkg/be/local/shell/job.go
- pkg/be/local/shell/pipe.go
- pkg/be/local/shell/spawn.go
- pkg/be/local/spawn.go
- pkg/be/local/streamer.go
- pkg/be/local/up.go
- pkg/lunchpail/component.go
the status UI still isn't functional for the local backend, but this is a necessary part of that larger work
> fix: implement `RunComponentUpdates` for local backend

- pkg/be/ibmcloud/qstat.go
- pkg/be/kubernetes/qstat.go
- pkg/be/local/streamer.go
- pkg/be/streamer/qstat.go
- pkg/be/streamer/streamer.go
- pkg/observe/qstat/qlast.go
- pkg/observe/qstat/ui.go
- pkg/observe/status/stream.go
As opposed to having the backend impls own these.
> fix: Streamer.QueueStats() api should place caller in control of goroutines and channels

- pkg/be/ibmcloud/utilization.go
- pkg/be/kubernetes/utilization-streamer.go
- pkg/be/kubernetes/utilization.go
- pkg/be/local/streamer.go
- pkg/be/streamer/streamer.go
- pkg/observe/cpu/ui.go
- pkg/observe/status/stream.go
As opposed to having the backend impls own these.
> fix: Streamer.Utilization() should place caller in charge of goroutines and channels

- pkg/be/local/runs.go
- pkg/be/local/shell/spawn.go
- pkg/be/local/streamer.go
- pkg/boot/up.go
- pkg/lunchpail/component.go
- pkg/observe/logs.go
- tests/bin/helpers.sh
This also simplifies the local log handling: only write to the file, and don't mmodify the output (leave that to the UI).
> feat: simplify up to stream logs only (for now)

- pkg/boot/down.go
- pkg/boot/up.go
This used to be more important, to reuse the up logic for down. Now it just obfuscates things.
> refactor: simply boot/up,down by avoiding needless reuse

- cmd/subcommands/build.go
- cmd/subcommands/component.go
- cmd/subcommands/dev.go
- cmd/subcommands/down.go
- cmd/subcommands/info.go
- cmd/subcommands/logs.go
- cmd/subcommands/queue.go
- cmd/subcommands/queue_full.go
- cmd/subcommands/root.go
- cmd/subcommands/status.go
- cmd/subcommands/up.go
> feat: group commands into user vs internal vs additional

- pkg/runtime/queue/s3.go
- pkg/runtime/workstealer/run.go
Falling back to polling if that s3 server does not support this api.
> feat: update workstealer to leverage push notifications

- tests/bin/helpers.sh
For no good reason, we are issuing a large number of `queue ls` commands to validate that the stdout and stderr files exist. Since we have already fetched a list of *all* output files, we can more simply just consult that list. Also this uses the same (new) check on the .code file.
This also removes the unnecessary check for the dispatcher done file (which result in more `queue ls` calls). This is unnecessary, since the main point of checking for the dispatcher done file was to validate that the dispatcher eventually self-destructs, which we check separately.
> test: reduce number of queue ls calls in test validators

- pkg/runtime/queue/enqueue.go
this also corrects a typo in enqueue s3 log output
> fix: remove leftover debug output from enqueue file

- cmd/subcommands/queue/done.go
- pkg/boot/up.go
- pkg/runtime/queue/qdone.go
> fix: `queue done` command should obey --verbose flag

- pkg/build/stage.go
- pkg/build/stage/appdir.go
- pkg/build/stage/getsource.go
- pkg/build/stage/helmignore.go
- pkg/build/stage/srcdir.go
- pkg/build/stage/stage.go
- pkg/build/stage/values.go
- pkg/build/stage/versionfile.go
This pulls out the individual parts of staging into separate files, and places them in a build/stage subdir. Hopefully this makes it easier to add more features to the staging process (e.g. requirements.txt)
> refactor: code cleanup of build/stage

- pkg/runtime/minio/server.go
we were sleeping aftert killing the process!
> fix: minio sleep before exit may do nothing

- tests/bin/run.sh
i think we may be running out of disk space in github actions
> test: in CI clean up python venvs

- .github/workflows/tests.yml
- cmd/subcommands/cat.go
- cmd/subcommands/groups.go
- cmd/subcommands/root.go
- pkg/be/local/shell/job.go
- pkg/be/local/shell/spawn.go
- pkg/be/local/shell/workdir.go
- pkg/be/local/spawn.go
- pkg/be/local/up.go
- pkg/be/runs/util/singleton.go
- pkg/boot/io.go
- pkg/boot/pipeline.go
- pkg/boot/up.go
- pkg/build/breadcrumbs.go
- pkg/fe/prepare-run.go
- pkg/fe/transformer/api/workerpool/lower.go
- pkg/ir/hlir/model.go
- pkg/ir/hlir/workerpool.go
- pkg/runtime/builtins/cat.go
- pkg/runtime/builtins/redirect.go
- pkg/runtime/worker/watcher.go
- pkg/util/term.go
- tests/bin/pipelines.sh
adds `tests/bin/pipelines.sh` for test coverage.
> feat: initial support for pipelines (starting with `cat` builtin)

- cmd/subcommands/component/workstealer/run.go
- pkg/fe/transformer/api/queue.go
- pkg/fe/transformer/api/workstealer/transpile.go
- pkg/runtime/queue/paths.go
- pkg/runtime/worker/watcher.go
- pkg/runtime/workstealer/assess.go
- pkg/runtime/workstealer/fetch.go
- pkg/runtime/workstealer/run.go
> fix: a few more path cleanups for workstealer

- cmd/subcommands/component/worker/prestop.go
- cmd/subcommands/component/worker/run.go
- pkg/fe/transformer/api/queue.go
- pkg/fe/transformer/api/workerpool/lower.go
- pkg/runtime/queue/paths.go
- pkg/runtime/worker/options.go
- pkg/runtime/worker/prestop.go
- pkg/runtime/worker/run.go
- pkg/runtime/worker/watcher.go
Alive and Dead and Bucket
plus some debug/verbose cleanups
> fix: first pass at cleaning up runtime/worker queue paths

- .gitignore
- tests/bin/pipelines.sh
Plus some cleanup to pipelines.sh
> test: add a few more pipeline tests

- cmd/subcommands/build.go
- pkg/be/local/shell/spawn.go
- pkg/fe/builder/build.go
- pkg/fe/builder/options.go
- pkg/fe/builder/overlay/eval.go
- pkg/fe/builder/overlay/overlay.go
- tests/bin/pipelines.sh
with this, an "add1" would be
```shell
./lunchpail build -e 'printf "%d" $((1+$(cat $1))) > $2' -o /tmp/add1
```
> feat: build --eval support

- cmd/subcommands/queue/stat.go
- hack/pipeline-demo.sh
- pkg/observe/qstat/renderer.go
- pkg/observe/qstat/ui.go
also
- tweak the appearance of dead workers
- increase the length of the pipeline in pipeline-demo
> fix: decrease default debounce interval for queue stat

- pkg/be/kubernetes/logs.go
- pkg/be/local/streamer.go
- pkg/be/streamer/streamer.go
- pkg/boot/watch.go
- pkg/observe/logs.go
For now, at least... this will help with seeing logs in pipelines.
> fix: logs to stderr

- cmd/subcommands/build.go
- hack/pipeline-demo.sh
- pkg/fe/builder/build.go
- pkg/fe/builder/options.go
- pkg/fe/builder/overlay/command.go
- pkg/fe/builder/overlay/overlay.go
- tests/bin/pipelines.sh
This should better align with `python -c` and `bash -c`
> fix: change --eval/-e to --command/-c

- cmd/options/build.go
- pkg/build/options.go
- pkg/fe/transformer/api/shell/lower.go
- tests/bin/pipelines.sh
> feat: add up -e/--env support

- pkg/fe/builder/overlay/command.go
- pkg/fe/transformer/api/minio/transpile.go
- pkg/fe/transformer/api/shell/lower.go
- pkg/fe/transformer/api/workerpool/lowerall.go
- pkg/fe/transformer/api/workstealer/needs.go
- pkg/fe/transformer/api/workstealer/transpile.go
- pkg/fe/transformer/application.go
- pkg/ir/hlir/application.go
- pkg/ir/hlir/model.go
- pkg/ir/hlir/role.go
- pkg/ir/hlir/workerpool.go
- pkg/runtime/builtins/add1.go
- pkg/runtime/builtins/cat.go
- pkg/runtime/builtins/sweep/sweep.go
- tests/bin/run.sh
- tests/tests/test0b/README.md
- tests/tests/test0b/pail/app.yaml
- tests/tests/test0b/settings.sh
This clarifies the set of roles: Worker vs Support
> feat: clean up hlir.Application.Spec.Role

- pkg/fe/builder/overlay/source.go
Also wrap a `strings.TrimSpace()` around the string-form usage.
> fix: when scanning appdir, avoid reading in files we will ignore
